# Generated by Django 4.1 on 2022-08-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_author_options_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(upload_to='blog/entries'),
        ),
    ]
